### ISSUE TITLE
Incompatible mod set!

### ISSUE THREAD

**Issue by CallumJThompson** [Wynntils/launchy#15]
Ever since installing the latest version of wynntils (0.0.2-alpha.374), I've been unable to launch Minecraft due to the latest version using 0.14.18 fabric loader. I've launched the mod launcher and there was some form of update button, clicked it, went to updates etc. and nothing seemed to change.

```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.11 with version 0.14.18 or later.
Unmet dependency listing:
	 - Mod 'Wynntils' (wynntils) 0.0.2-alpha.374 requires version 0.14.18 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.11!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by DevScyu** [comment]
Fiixed
