### ISSUE TITLE
Wynntils not working for me.

### ISSUE THREAD

**Issue by DogFatherNas** [Wynntils/launchy#6]
I cannot launch the game. Whenever I try I get the incompatible mod pack set. I haven't put in any mods and I only use the ones that the wynntils mod installer allows. I've tried deleting EVERYTHING except the core and it still wont work.

**Comment by Zonar7** [comment]
I have the same issue

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.11 with version 0.14.18 or later.
Unmet dependency listing:
	 - Mod 'WynnLibFabric' (wynnlib) 0.2.9-1.19.3 requires version 0.14.14 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.11!
	 - Mod 'Wynntils' (wynntils) 0.0.2-alpha.402 requires version 0.14.18 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.11!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MinerMinerMods** [comment]
Hello, thank you for sharing the debug log.
This debug log is highly readable to the average person with reasonable technological skills but if you would like it simplified, you need to update the Loader for fabric due to it being behind by 3 versions for both, this means that Fabric failed to get updated. If you can search for a update button to fabric or download [Fabric](https://fabricmc.net/use/installer/) again. If you do not know how to download this contact anyone from [wynntils discord](https://discord.com/channels/394189072635133952/1038478657225752606) (edited to change the discord URL to the directly related content)

**Comment by kristofbolyai** [comment]
If you download the latest launchy, 1.3.0, it most likely will auto update everything for you.
